<?php
$labels = array();
$labels['pluginname'] = 'حسابات SMTP الخارجية';
$labels['plugindescription'] = 'ربط مرحلات SMTP بهويات الحسابات على مستوى كل مستخدم.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'ممكّنة';
$labels['smtpserver'] = 'خادم SMTP';
$labels['smtpuser'] = 'اسم المستخدم';
$labels['smtppass'] = 'كلمة المرور';
$labels['isset'] = 'كلمة المرور المحفوظة بالفعل';
$labels['isnotset'] = 'الرجاء إدخال كلمة المرور';
$labels['ie'] = 'أي:';
$labels['nosavesent'] = 'يقوم الخادم بحفظ رسائل البريد المرسلة إلى المرسلة';
?>
