<?php
$labels = array();
$labels['pluginname'] = 'Външни SMTP акаунти';
$labels['plugindescription'] = 'Свързване на SMTP ретранслатори с идентичностите на акаунта на ниво потребител.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Разрешено';
$labels['smtpserver'] = 'SMTP сървър';
$labels['smtpuser'] = 'Потребителско име';
$labels['smtppass'] = 'Парола';
$labels['isset'] = 'Паролата вече е записана';
$labels['isnotset'] = 'Моля, въведете парола';
$labels['ie'] = 'т.е.:';
$labels['nosavesent'] = 'Сървърът записва изпратените писма в Sent';
?>
