<?php
$labels = array();
$labels['pluginname'] = 'Externí účty SMTP';
$labels['plugindescription'] = 'Přiřazení relé SMTP k identitám účtu na úrovni jednotlivých uživatelů.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Povoleno';
$labels['smtpserver'] = 'Server SMTP';
$labels['smtpuser'] = 'Uživatelské jméno';
$labels['smtppass'] = 'Heslo';
$labels['isset'] = 'Heslo je již uloženo';
$labels['isnotset'] = 'Zadejte prosím heslo';
$labels['ie'] = 'tj:';
$labels['nosavesent'] = 'Server ukládá odeslané e-maily do složky Odeslané';
?>
