// Identities SMTP Plugin for Roundcube

<?php
$labels=array();
$labels['pluginname']='Externí SMTP účty';
$labels['plugindescription']='Přiřadí odchozí SMTP servery k danému lokálnímu účtu.';
$labels['smtp']='SMTP';
$labels['enabled']='Povolen';
$labels['smtpserver']='SMTP server';
$labels['smtpuser']='Uživatelské jméno';
$labels['smtppass']='Heslo';
$labels['isset']='Heslo je již uloženo';
$labels['isnotset']='Zadejte prosím heslo';
$labels['fe']='např.';