<?php
$labels = array();
$labels['pluginname'] = 'Eksterne SMTP-konti';
$labels['plugindescription'] = 'Tilknyt SMTP-relæer til kontoidentiteter på brugerniveau.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Aktiveret';
$labels['smtpserver'] = 'SMTP-server';
$labels['smtpuser'] = 'Brugernavn';
$labels['smtppass'] = 'Adgangskode';
$labels['isset'] = 'Adgangskode allerede gemt';
$labels['isnotset'] = 'Indtast venligst adgangskode';
$labels['ie'] = 'dvs:';
$labels['nosavesent'] = 'Serveren gemmer sendte mails i Sent';
?>
