<?php
$labels = array();
$labels['pluginname'] = 'Externe SMTP-Konten';
$labels['plugindescription'] = 'Verknüpfen Sie SMTP-Relays mit den Identitäten der Konten auf Benutzerebene.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Aktiviert';
$labels['smtpserver'] = 'SMTP-Server';
$labels['smtpuser'] = 'Benutzername';
$labels['smtppass'] = 'Passwort';
$labels['isset'] = 'Passwort bereits gespeichert';
$labels['isnotset'] = 'Bitte Passwort eingeben';
$labels['ie'] = 'd.h.:';
$labels['nosavesent'] = 'Server speichert gesendete Mails in Gesendet';
?>
