// Identities SMTP Plugin for Roundcube

<?php
$labels=array();
$labels['pluginname']='Externe SMTP Konten';
$labels['plugindescription']='Jeder Identität einen entsprechenden SMTP-Server auf Benutzerebene zuordnen.';
$labels['smtp']='SMTP';
$labels['enabled']='Aktiviert';
$labels['smtpserver']='SMTP-Server';
$labels['smtpuser']='Benutzername';
$labels['smtppass']='Passwort';
$labels['isset']='Passwort ist gespeichert';
$labels['isnotset']='Passwort eingeben';
$labels['fe']='z.B.:';