<?php
$labels = array();
$labels['pluginname'] = 'Εξωτερικοί λογαριασμοί SMTP';
$labels['plugindescription'] = 'Συνδέστε αναμεταδότες SMTP με ταυτότητες λογαριασμού σε επίπεδο χρήστη.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Ενεργοποιημένο';
$labels['smtpserver'] = 'Διακομιστής SMTP';
$labels['smtpuser'] = 'Όνομα χρήστη';
$labels['smtppass'] = 'Κωδικός πρόσβασης';
$labels['isset'] = 'Ο κωδικός πρόσβασης έχει ήδη αποθηκευτεί';
$labels['isnotset'] = 'Παρακαλώ εισάγετε τον κωδικό πρόσβασης';
$labels['ie'] = 'δηλ:';
$labels['nosavesent'] = 'Ο διακομιστής αποθηκεύει τα απεσταλμένα μηνύματα στο Sent';
?>
