// Identities SMTP Plugin for Roundcube

<?php
$labels=array();
$labels['pluginname']='External SMTP Accounts';
$labels['plugindescription']='Associate SMTP relays to account\'s identities on a per user level.';
$labels['smtp']='SMTP';
$labels['enabled']='Enabled';
$labels['smtpserver']='SMTP server';
$labels['smtpuser']='Username';
$labels['smtppass']='Password';
$labels['isset']='Password already saved';
$labels['isnotset']='Please enter Password';
$labels['ie']='i.e.:';
$labels['nosavesent']='Server saves sent mails to Sent';