// Identities SMTP Plugin for Roundcube

<?php
$labels=array();
$labels['pluginname']='Identidades SMTP';
$labels['plugindescription']='Asociar transmisores SMTP con identidades de cuentas a nivel de usuario.';
$labels['smtp']='SMTP';
$labels['enabled']='Habilitado';
$labels['smtpserver']='Servidor SMTP';
$labels['smtpuser']='Nombre de usuario';
$labels['smtppass']='Contraseña';
$labels['isset']='Contraseña ya ha sido guardada';
$labels['isnotset']='Por favor, introduzca su contraseña';