<?php
$labels = array();
$labels['pluginname'] = 'Cuentas SMTP externas';
$labels['plugindescription'] = 'Asociar relés SMTP a identidades de cuenta a nivel de usuario.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Activado';
$labels['smtpserver'] = 'Servidor SMTP';
$labels['smtpuser'] = 'Nombre de usuario';
$labels['smtppass'] = 'Contraseña';
$labels['isset'] = 'Contraseña ya guardada';
$labels['isnotset'] = 'Introduzca la contraseña';
$labels['ie'] = 'es decir:';
$labels['nosavesent'] = 'El servidor guarda los correos enviados en Enviados';
?>
