<?php
$labels = array();
$labels['pluginname'] = 'Välised SMTP kontod';
$labels['plugindescription'] = 'Seostage SMTP-redelid konto identiteediga kasutaja tasandil.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Lubatud';
$labels['smtpserver'] = 'SMTP server';
$labels['smtpuser'] = 'Kasutajanimi';
$labels['smtppass'] = 'Parool';
$labels['isset'] = 'Parool on juba salvestatud';
$labels['isnotset'] = 'Palun sisestage salasõna';
$labels['ie'] = 'st:';
$labels['nosavesent'] = 'Server salvestab saadetud kirjad aadressile Sent';
?>
