<?php
$labels = array();
$labels['pluginname'] = 'Ulkoiset SMTP-tilit';
$labels['plugindescription'] = 'Yhdistä SMTP-välityspalvelimet tilien tunnuksiin käyttäjäkohtaisesti.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Käytössä';
$labels['smtpserver'] = 'SMTP-palvelin';
$labels['smtpuser'] = 'Käyttäjätunnus';
$labels['smtppass'] = 'Salasana';
$labels['isset'] = 'Salasana on jo tallennettu';
$labels['isnotset'] = 'Anna salasana';
$labels['ie'] = 'ts:';
$labels['nosavesent'] = 'Palvelin tallentaa lähetetyt sähköpostit osoitteeseen Sent';
?>
