// Identities SMTP Plugin for Roundcube

<?php
$labels=array();
$labels['pluginname']='Comptes SMTP externes';
$labels['smtp']='SMTP';
$labels['enabled']='Activé';
$labels['smtpserver']='Serveur SMTP';
$labels['smtpuser']='Nom d\'utilisateur';
$labels['smtppass']='Mot de passe';
$labels['isset']='Mot de passe déjà sauvegardé';
$labels['isnotset']='Veuillez entrer votre mot de passe';
$labels['fe']='Par exemple:';