<?php
$labels = array();
$labels['pluginname'] = 'Comptes SMTP externes';
$labels['plugindescription'] = 'Associer les relais SMTP aux identités des comptes au niveau de chaque utilisateur.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Activé';
$labels['smtpserver'] = 'Serveur SMTP';
$labels['smtpuser'] = 'Nom d\'utilisateur';
$labels['smtppass'] = 'Mot de passe';
$labels['isset'] = 'Mot de passe déjà enregistré';
$labels['isnotset'] = 'Veuillez saisir votre mot de passe';
$labels['ie'] = 'c\'est-à-dire :';
$labels['nosavesent'] = 'Le serveur enregistre les messages envoyés dans Sent';
?>
