<?php
$labels = array();
$labels['pluginname'] = 'חשבונות SMTP חיצוניים';
$labels['plugindescription'] = 'שייך ממסרי SMTP לזהויות החשבון ברמת המשתמש.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'מופעל';
$labels['smtpserver'] = 'שרת SMTP';
$labels['smtpuser'] = 'שם משתמש';
$labels['smtppass'] = 'סיסמה';
$labels['isset'] = 'הסיסמה כבר נשמרה';
$labels['isnotset'] = 'אנא הזן סיסמה';
$labels['ie'] = 'כלומר:';
$labels['nosavesent'] = 'השרת שומר את הדואר שנשלח בתיקיית "נשלח"';
?>
