<?php
$labels = array();
$labels['pluginname'] = 'Külső SMTP-fiókok';
$labels['plugindescription'] = 'Az SMTP-továbbítók hozzárendelése a fiókok azonosítóihoz felhasználói szinten.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Engedélyezve';
$labels['smtpserver'] = 'SMTP-kiszolgáló';
$labels['smtpuser'] = 'Felhasználónév';
$labels['smtppass'] = 'Jelszó';
$labels['isset'] = 'Jelszó már elmentve';
$labels['isnotset'] = 'Kérjük, adja meg a jelszót';
$labels['ie'] = 'azaz:';
$labels['nosavesent'] = 'A kiszolgáló az elküldött leveleket a Sent';
?>
