<?php
$labels = array();
$labels['pluginname'] = 'Akun SMTP Eksternal';
$labels['plugindescription'] = 'Mengaitkan relai SMTP ke identitas akun pada tingkat per pengguna.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Diaktifkan';
$labels['smtpserver'] = 'Server SMTP';
$labels['smtpuser'] = 'Nama pengguna';
$labels['smtppass'] = 'Kata sandi';
$labels['isset'] = 'Kata sandi sudah disimpan';
$labels['isnotset'] = 'Silakan masukkan Kata Sandi';
$labels['ie'] = 'yaitu:';
$labels['nosavesent'] = 'Server menyimpan email yang dikirim ke Terkirim';
?>
