<?php
$labels = array();
$labels['pluginname'] = 'Account SMTP esterni';
$labels['plugindescription'] = 'Associare i relè SMTP alle identità degli account a livello di singolo utente.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Abilitato';
$labels['smtpserver'] = 'Server SMTP';
$labels['smtpuser'] = 'Nome utente';
$labels['smtppass'] = 'Password';
$labels['isset'] = 'Password già salvata';
$labels['isnotset'] = 'Inserire la password';
$labels['ie'] = 'cioè:';
$labels['nosavesent'] = 'Il server salva le mail inviate in Sent';
?>
