<?php
$labels = array();
$labels['pluginname'] = '外部SMTPアカウント';
$labels['plugindescription'] = 'SMTPリレーをユーザーごとにアカウントのIDに関連付ける。';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = '有効';
$labels['smtpserver'] = 'SMTPサーバー';
$labels['smtpuser'] = 'ユーザー名';
$labels['smtppass'] = 'パスワード';
$labels['isset'] = 'パスワードは保存済み';
$labels['isnotset'] = 'パスワードを入力してください';
$labels['ie'] = 'すなわち：';
$labels['nosavesent'] = 'サーバーは送信済みメールをSentに保存';
?>
