<?php
$labels = array();
$labels['pluginname'] = '외부 SMTP 계정';
$labels['plugindescription'] = '사용자 단위로 SMTP 릴레이를 계정의 ID에 연결합니다.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = '활성화됨';
$labels['smtpserver'] = 'SMTP 서버';
$labels['smtpuser'] = '사용자 이름';
$labels['smtppass'] = '비밀번호';
$labels['isset'] = '이미 저장된 비밀번호';
$labels['isnotset'] = '비밀번호를 입력하세요';
$labels['ie'] = '즉.:';
$labels['nosavesent'] = '서버는 보낸 메일을 보낸 사람에 저장합니다';
?>
