<?php
$labels = array();
$labels['pluginname'] = 'Išorinės SMTP paskyros';
$labels['plugindescription'] = 'SMTP retransliatorių susiejimas su paskyros tapatybėmis kiekvieno naudotojo lygmeniu.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Įjungta';
$labels['smtpserver'] = 'SMTP serveris';
$labels['smtpuser'] = 'Vartotojo vardas';
$labels['smtppass'] = 'Slaptažodis';
$labels['isset'] = 'Slaptažodis jau išsaugotas';
$labels['isnotset'] = 'Įveskite slaptažodį';
$labels['ie'] = 't. y.:';
$labels['nosavesent'] = 'Serveris išsaugo išsiųstus laiškus į "Sent';
?>
