<?php
$labels = array();
$labels['pluginname'] = 'Ārējie SMTP konti';
$labels['plugindescription'] = 'SMTP releju piesaistīšana konta identitātēm katra lietotāja līmenī.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Ieslēgts';
$labels['smtpserver'] = 'SMTP serveris';
$labels['smtpuser'] = 'Lietotājvārds';
$labels['smtppass'] = 'Parole';
$labels['isset'] = 'Parole jau saglabāta';
$labels['isnotset'] = 'Lūdzu, ievadiet paroli';
$labels['ie'] = 't.i.:';
$labels['nosavesent'] = 'Serveris saglabā nosūtītos e-pastus uz Nosūtīts';
?>
