<?php
$labels = array();
$labels['pluginname'] = 'Externe SMTP-accounts';
$labels['plugindescription'] = 'SMTP-relais koppelen aan accountidentiteiten op gebruikersniveau.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Ingeschakeld';
$labels['smtpserver'] = 'SMTP-server';
$labels['smtpuser'] = 'Gebruikersnaam';
$labels['smtppass'] = 'Wachtwoord';
$labels['isset'] = 'Wachtwoord al opgeslagen';
$labels['isnotset'] = 'Voer wachtwoord in';
$labels['ie'] = 'dat wil zeggen:';
$labels['nosavesent'] = 'Server slaat verzonden mails op in Verzonden';
?>
