<?php
$labels = array();
$labels['pluginname'] = 'Eksterne SMTP-kontoer';
$labels['plugindescription'] = 'Knytt SMTP-reléer til kontoidentiteter på brukernivå.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Aktivert';
$labels['smtpserver'] = 'SMTP-server';
$labels['smtpuser'] = 'Brukernavn';
$labels['smtppass'] = 'Passord';
$labels['isset'] = 'Passordet er allerede lagret';
$labels['isnotset'] = 'Vennligst skriv inn passord';
$labels['ie'] = 'dvs:';
$labels['nosavesent'] = 'Serveren lagrer sendte e-poster i Sent';
?>
