<?php
$labels = array();
$labels['pluginname'] = 'Zewnętrzne konta SMTP';
$labels['plugindescription'] = 'Powiązanie przekaźników SMTP z tożsamościami konta na poziomie użytkownika.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Włączone';
$labels['smtpserver'] = 'Serwer SMTP';
$labels['smtpuser'] = 'Nazwa użytkownika';
$labels['smtppass'] = 'Hasło';
$labels['isset'] = 'Hasło zostało już zapisane';
$labels['isnotset'] = 'Wprowadź hasło';
$labels['ie'] = 'tj:';
$labels['nosavesent'] = 'Serwer zapisuje wysłane wiadomości do Sent';
?>
