// Identities SMTP Plugin for Roundcube

<?php
$labels=array();
$labels['pluginname']='Zewnętrzne konta SMTP';
$labels['plugindescription']='Umożliwia powiązanie ustawień przekaźnika SMTP z tożsamościami na poziomie użytkownika.';
$labels['smtp']='SMTP';
$labels['enabled']='Włączone';
$labels['smtpserver']='Serwer SMTP';
$labels['smtpuser']='Nazwa użytkownika';
$labels['smtppass']='Hasło';
$labels['isset']='Hasło już jest zachowane';
$labels['isnotset']='Proszę podać hasło';