<?php
$labels = array();
$labels['pluginname'] = 'Contas SMTP externas';
$labels['plugindescription'] = 'Associe retransmissões SMTP às identidades da conta em um nível por usuário.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Ativado';
$labels['smtpserver'] = 'Servidor SMTP';
$labels['smtpuser'] = 'Nome de usuário';
$labels['smtppass'] = 'Senha';
$labels['isset'] = 'Senha já salva';
$labels['isnotset'] = 'Digite a senha';
$labels['ie'] = 'ou seja:';
$labels['nosavesent'] = 'O servidor salva os e-mails enviados em Sent';
?>
