<?php
$labels = array();
$labels['pluginname'] = 'Conturi SMTP externe';
$labels['plugindescription'] = 'Asocierea releelor SMTP la identitățile conturilor la nivel de utilizator.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Activat';
$labels['smtpserver'] = 'Server SMTP';
$labels['smtpuser'] = 'Nume utilizator';
$labels['smtppass'] = 'Parolă';
$labels['isset'] = 'Parolă deja salvată';
$labels['isnotset'] = 'Vă rugăm să introduceți parola';
$labels['ie'] = 'i.e.:';
$labels['nosavesent'] = 'Serverul salvează e-mailurile trimise în Sent';
?>
