<?php
$labels = array();
$labels['pluginname'] = 'Внешние учетные записи SMTP';
$labels['plugindescription'] = 'Привязка SMTP-реле к учетным записям на уровне каждого пользователя.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Включено';
$labels['smtpserver'] = 'SMTP-сервер';
$labels['smtpuser'] = 'Имя пользователя';
$labels['smtppass'] = 'Пароль';
$labels['isset'] = 'Пароль уже сохранен';
$labels['isnotset'] = 'Пожалуйста, введите пароль';
$labels['ie'] = 'т.е:';
$labels['nosavesent'] = 'Сервер сохраняет отправленные сообщения в папке Sent';
?>
