<?php
$labels = array();
$labels['pluginname'] = 'Externé účty SMTP';
$labels['plugindescription'] = 'Priradenie relé SMTP k identitám účtu na úrovni jednotlivých používateľov.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Povolené';
$labels['smtpserver'] = 'Server SMTP';
$labels['smtpuser'] = 'Používateľské meno';
$labels['smtppass'] = 'Heslo';
$labels['isset'] = 'Heslo je už uložené';
$labels['isnotset'] = 'Zadajte heslo';
$labels['ie'] = 't. j.:';
$labels['nosavesent'] = 'Server ukladá odoslané e-maily do položky Odoslané';
?>
