<?php
$labels = array();
$labels['pluginname'] = 'Zunanji računi SMTP';
$labels['plugindescription'] = 'Povezovanje posrednikov SMTP z identitetami računov na ravni posameznega uporabnika.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Omogočeno';
$labels['smtpserver'] = 'Strežnik SMTP';
$labels['smtpuser'] = 'Uporabniško ime';
$labels['smtppass'] = 'Geslo';
$labels['isset'] = 'Geslo je že shranjeno';
$labels['isnotset'] = 'Vnesite geslo';
$labels['ie'] = 't.j.:';
$labels['nosavesent'] = 'Strežnik shrani poslano pošto v Sent';
?>
