<?php
$labels = array();
$labels['pluginname'] = 'Externa SMTP-konton';
$labels['plugindescription'] = 'Koppla SMTP-reläer till kontonas identiteter på en nivå per användare.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Aktiverad';
$labels['smtpserver'] = 'SMTP-server';
$labels['smtpuser'] = 'Användarnamn';
$labels['smtppass'] = 'Lösenord';
$labels['isset'] = 'Lösenordet är redan sparat';
$labels['isnotset'] = 'Vänligen ange lösenord';
$labels['ie'] = 'dvs:';
$labels['nosavesent'] = 'Servern sparar skickade e-postmeddelanden i Sent';
?>
