<?php
$labels = array();
$labels['pluginname'] = 'Harici SMTP Hesapları';
$labels['plugindescription'] = 'SMTP aktarımlarını kullanıcı bazında hesap kimlikleriyle ilişkilendirin.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Etkin';
$labels['smtpserver'] = 'SMTP sunucusu';
$labels['smtpuser'] = 'Kullanıcı Adı';
$labels['smtppass'] = 'Şifre';
$labels['isset'] = 'Şifre zaten kaydedilmiş';
$labels['isnotset'] = 'Lütfen Şifre Giriniz';
$labels['ie'] = 'yani:';
$labels['nosavesent'] = 'Sunucu gönderilen postaları Gönderilenler\'e kaydeder';
?>
