<?php
$labels = array();
$labels['pluginname'] = 'Зовнішні SMTP-акаунти';
$labels['plugindescription'] = 'Асоційований SMTP ретранслює ідентифікатори облікових записів на рівні кожного користувача.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Увімкнено';
$labels['smtpserver'] = 'SMTP-сервер';
$labels['smtpuser'] = 'Ім\'я користувача';
$labels['smtppass'] = 'Пароль';
$labels['isset'] = 'Пароль вже збережено';
$labels['isnotset'] = 'Будь ласка, введіть Пароль';
$labels['ie'] = 'тобто:';
$labels['nosavesent'] = 'Сервер зберігає надіслані листи у папці "Надіслані';
?>
