<?php
$labels = array();
$labels['pluginname'] = 'Tài khoản SMTP bên ngoài';
$labels['plugindescription'] = 'Kết nối các máy chủ SMTP trung gian với các danh tính của tài khoản trên từng người dùng.';
$labels['smtp'] = 'SMTP';
$labels['enabled'] = 'Đã bật';
$labels['smtpserver'] = 'Máy chủ SMTP';
$labels['smtpuser'] = 'Tên đăng nhập';
$labels['smtppass'] = 'Mật khẩu';
$labels['isset'] = 'Mật khẩu đã được lưu';
$labels['isnotset'] = 'Vui lòng nhập mật khẩu';
$labels['ie'] = 'ví dụ:';
$labels['nosavesent'] = 'Máy chủ lưu trữ các email đã gửi vào thư mục "Đã gửi"';
?>
